// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WizardIngredients.Data;

#nullable disable

namespace WizardIngredients.Migrations
{
    [DbContext(typeof(IngredienteDbContext))]
    [Migration("20240913002530_MigrationInicial")]
    partial class MigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WizardIngredients.Data.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alergicos")
                        .HasColumnType("TEXT");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfNutri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingrediente");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Alergicos = "Glútem",
                            Categoria = "Cereais",
                            InfNutri = "[\"Calorias: 20 kcal\",\"Carboidratos: 20 g\",\"Gorduras Totais: 0 g\"]",
                            Nome = "Trigo"
                        },
                        new
                        {
                            Id = 1002,
                            Alergicos = "Castanhas",
                            Categoria = "Cereais",
                            InfNutri = "[\"Calorias: 50 kcal\",\"Carboidratos: 2 g\",\"Gorduras Totais: 70 g\"]",
                            Nome = "Amendoim"
                        },
                        new
                        {
                            Id = 1003,
                            Alergicos = "Nenhum",
                            Categoria = "Fruta",
                            InfNutri = "[\"Calorias: 89 kcal\",\"Carboidratos: 1 g\",\"Gorduras Totais: 0 g\"]",
                            Nome = "Tomate"
                        },
                        new
                        {
                            Id = 1004,
                            Alergicos = "Nenhum",
                            Categoria = "Folhas",
                            InfNutri = "[\"Calorias: 20 kcal\",\"Carboidratos: 0 g\",\"Gorduras Totais: 0 g\"]",
                            Nome = "Alface"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
